(() => {
  const root=document.getElementById('forever-young-pet-ui');
  const words={
    zh:{tools:'陪伴工具',history:'通知历史',empty:'暂无记录',all:'全部',jump:'打开任务 / 控制台',clear:'清空历史',recent:'最近执行目标',timing:'任务计时（从本机首次收到状态起）',timer:'番茄钟',work:'专注',rest:'休息',idle:'未开始',start:'开始',pause:'暂停',resume:'继续',reset:'结束',minutes:'专注分钟',normal:'普通',focus:'专注 · 暂停自动气泡和语音',meeting:'会议 · 暂停自动气泡并静音',mode:'陪伴模式',edge:'收起到屏幕右侧',voice:'语音设置',volume:'音量',enabled:'角色语音',auto:'自动状态语音',click:'点击问候',working:'工作中',completed:'已完成',failed:'失败',interrupted:'中断',waiting:'等待',review:'检查',disconnected:'未连接',audition:'试听',quiet:'免打扰时段',hours:'本机时间；开始与结束相同表示全天静音。试听由你主动触发，可绕过静音时段。',racing:'赛事提醒与日历',raceReminders:'已确认时刻的开赛提醒',entryReminders:'候选 → 正式出走提醒',lead:'提前分钟',export:'导出 .ics',candidate:'候选 / 未确认',declared:'正式出走',tba:'时刻未确认',diagnostics:'连接诊断',check:'重新检查连接',version:'插件 / 内置版本',heartbeat:'最近心跳',runtime:'当前文件解释器 / 编译器',target:'将运行的目标',file:'当前文件',choose:'首次需在 IDE 选择目标',old:'需要更新附带的 3.8.0 插件',manual:'使用说明在设置中；未安装插件时请按说明安装。',local:'应用运行时，本地检查与提醒；关闭应用后不提醒。未确认时刻按当地日期导出全天日历。',notification:'只保存摘要，最多 200 条；清空后无法恢复。',restStart:'开始休息',restEnd:'休息结束',raceStart:'即将开赛',raceDeclared:'正式出走已确认',record:'Codex 本地记录',official:'Codex 官方通道',connected:'已连接',unavailable:'未报告 / 不适用',trusted:'工作区已信任',notTrusted:'工作区未信任',problems:'打开问题面板'},
    ja:{tools:'サポート',history:'通知履歴',empty:'記録なし',all:'すべて',jump:'タスク / コンソール',clear:'履歴を消去',recent:'最近の実行対象',timing:'計測時間（ローカル受信時点から）',timer:'ポモドーロ',work:'集中',rest:'休憩',idle:'未開始',start:'開始',pause:'一時停止',resume:'再開',reset:'終了',minutes:'集中時間（分）',normal:'通常',focus:'集中 · 自動通知と音声を停止',meeting:'会議 · 自動通知を停止し消音',mode:'モード',edge:'画面右端に収納',voice:'音声設定',volume:'音量',enabled:'キャラクター音声',auto:'自動状態音声',click:'クリック挨拶',working:'作業中',completed:'完了',failed:'失敗',interrupted:'中断',waiting:'待機',review:'確認',disconnected:'未接続',audition:'試聴',quiet:'静音時間',hours:'端末の時刻。開始と終了が同じなら終日静音。試聴は手動操作のため静音時間中も再生します。',racing:'レース通知とカレンダー',raceReminders:'確定した発走時刻を通知',entryReminders:'候補 → 正式出走を通知',lead:'通知する何分前',export:'.ics を保存',candidate:'候補 / 未確定',declared:'出走確定',tba:'時刻未確定',diagnostics:'接続診断',check:'接続を再確認',version:'プラグイン / 内蔵版',heartbeat:'最終受信',runtime:'インタープリター / コンパイラ',target:'実行予定の対象',file:'現在のファイル',choose:'初回は IDE で対象を選択',old:'同梱の 3.8.0 プラグインへ更新',manual:'使い方とインストール手順は設定内のガイドにあります。',local:'アプリ起動中のみローカルで通知します。時刻未確定は開催地の日付で終日予定として保存。',notification:'要約のみ最大 200 件。削除した履歴は復元できません。',restStart:'休憩開始',restEnd:'休憩終了',raceStart:'まもなく発走',raceDeclared:'出走正式確定',record:'Codex ローカル記録',official:'Codex 公式 API',connected:'接続済み',unavailable:'未報告 / 対象外',trusted:'信頼済みワークスペース',notTrusted:'未信頼ワークスペース',problems:'問題パネルを開く'},
    en:{tools:'Companion tools',history:'Notification history',empty:'No records',all:'All',jump:'Open task / console',clear:'Clear history',recent:'Recent execution targets',timing:'Task timing (since first local status)',timer:'Pomodoro',work:'Focus',rest:'Break',idle:'Not started',start:'Start',pause:'Pause',resume:'Resume',reset:'End',minutes:'Focus minutes',normal:'Normal',focus:'Focus · Pause automatic bubbles and voice',meeting:'Meeting · Pause automatic bubbles and mute',mode:'Companion mode',edge:'Park at right screen edge',voice:'Voice settings',volume:'Volume',enabled:'Character voice',auto:'Automatic status voice',click:'Click greeting',working:'Working',completed:'Completed',failed:'Failed',interrupted:'Interrupted',waiting:'Waiting',review:'Review',disconnected:'Disconnected',audition:'Audition',quiet:'Quiet hours',hours:'Device time. Equal start/end means all day. Explicit audition bypasses quiet hours.',racing:'Race reminders & calendar',raceReminders:'Confirmed start-time reminders',entryReminders:'Candidate → declared entry alerts',lead:'Minutes before start',export:'Export .ics',candidate:'Candidate / unconfirmed',declared:'Declared entry',tba:'Time unconfirmed',diagnostics:'Connection diagnostics',check:'Recheck connections',version:'Plugin / built-in version',heartbeat:'Last heartbeat',runtime:'Current-file interpreter / compiler',target:'Target to run',file:'Current file',choose:'Choose a target in the IDE on first use',old:'Update to the bundled 3.8.0 bridge',manual:'Installation and connection instructions are in Settings.',local:'Reminders run locally while the app is open. Unconfirmed times export as all-day events on the local venue date.',notification:'Summaries only, up to 200 records. Cleared history cannot be restored.',restStart:'Break started',restEnd:'Break ended',raceStart:'Race starts soon',raceDeclared:'Entry declared',record:'Codex local records',official:'Official Codex API',connected:'Connected',unavailable:'Not reported / not applicable',trusted:'Trusted workspace',notTrusted:'Untrusted workspace',problems:'Open Problems'}
  };
  const language=()=>root.lang.startsWith('zh')?'zh':root.lang==='ja'?'ja':'en';
  const t=k=>words[language()][k] || k;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const send=(command,values={})=>window.webkit?.messageHandlers?.pet?.postMessage({command,...values});
  const button=(label,cmd,attrs='')=>`<button type="button" class="fy-action" data-command="${cmd}" ${attrs}>${esc(t(label))}</button>`;
  let data={preferences:{},history:[],recent:[],timer:{phase:'idle',seconds:0},diagnostics:{sources:[]},races:[],running:[]},filter='all',fingerprint='';
  for(const surface of root.querySelectorAll('[data-ui-surface]')) {
    const panel=document.createElement('div');panel.className=surface.dataset.uiSurface==='anime'?'uma-panel':'fy-horse-panel';panel.setAttribute(surface.dataset.uiSurface==='anime'?'data-uma-panel':'data-panel','tools');panel.hidden=true;
    surface.querySelector(surface.dataset.uiSurface==='anime'?'[data-uma-panel=integrations]':'[data-panel=integrations]').after(panel);
    const settings=document.createElement('div');settings.dataset.toolSettings='';surface.querySelector('.fy-settings').append(settings);
  }
  const checkbox=(key,label,p)=>`<label class="fy-tool-check"><input type="checkbox" data-tool-key="${key}" ${p[key]?'checked':''}>${esc(t(label))}</label>`;
  const select=(key,values,p)=>`<select data-tool-key="${key}">${values.map(([value,label])=>`<option value="${value}" ${String(p[key])===String(value)?'selected':''}>${esc(label)}</option>`).join('')}</select>`;
  function diagnostics() {
    const sources=data.diagnostics?.sources || [];
    return `<p>${esc(t('record'))}: ${esc(t(data.codexRecordConnected?'connected':'disconnected'))}<br>${esc(t('official'))}: ${esc(data.official?.ready?(data.official.transport || t('connected')):data.official?.message || t('disconnected'))}</p>`+sources.map(s=>{
      const m=s.metadata || {};
      return `<article class="fy-diagnostic"><h4>${esc(s.label)} · ${esc(t(s.connected?'connected':'disconnected'))}</h4><dl><dt>${esc(t('version'))}</dt><dd>${esc(m.pluginVersion || t('unavailable'))} · ${esc(m.ideVersion || '')}</dd><dt>${esc(t('heartbeat'))}</dt><dd>${esc(s.sentAt?new Date(s.sentAt).toLocaleString(root.lang):'—')}</dd><dt>${esc(t('runtime'))}</dt><dd>${esc(m.runtime || t('unavailable'))}</dd><dt>${esc(t('target'))}</dt><dd>${esc(m.runTarget || t('choose'))}</dd><dt>${esc(t('file'))}</dt><dd>${esc(m.file || '—')}</dd></dl>${s.source==='vscode'?`<p>${esc(t(m.trusted==='true'?'trusted':'notTrusted'))}</p>`:''}${m.diagnosticError?`<p class="fy-notice">${esc(m.diagnosticError)}</p>`:''}${s.source!=='codex'&&m.pluginVersion!=='3.8.0'?`<p class="fy-notice">${esc(t('old'))}</p>`:''}</article>`;
    }).join('')+button('check','diagnose')+`<p>${esc(t('manual'))}</p>`;
  }
  const versionWords={
    zh:{title:'版本更新与回退',current:'当前 App',check:'检查 GitHub 更新',download:'打开下载页面',import:'导入解压后的完整版本',plugins:'打开配套插件',switch:'切换到此版本',idle:'可检查更新或导入本地版本。',checking:'正在检查…',unpublished:'GitHub 尚未发布可识别的更新清单；可导入本地成品。',checkFailed:'在线检查失败。',available:'有新版可用',latest:'远程没有更高版本',verifying:'正在校验并备份当前版本…',imported:'版本已导入；当前 App 保持运行，选择切换后生效。',importFailed:'导入失败；当前 App 保留。',help:'整套版本包含 App 与两个配套插件。切换前安装对应插件并重载／重启 IDE；旧插件仍可接收状态，新增运行功能需要版本匹配。运行任务未结束时禁止切换。校验包内完整性不代表 Apple 公证。'},
    ja:{title:'更新とロールバック',current:'現在の App',check:'GitHub の更新を確認',download:'ダウンロードを開く',import:'展開済みの完全版を導入',plugins:'対応プラグインを開く',switch:'このバージョンへ切替',idle:'更新の確認、またはローカル版を導入できます。',checking:'確認中…',unpublished:'更新マニフェストは未公開です。ローカル版を導入できます。',checkFailed:'オンライン確認失敗。',available:'新版があります',latest:'新しいリモート版はありません',verifying:'検証して現在の版をバックアップ中…',imported:'導入済み。切り替えるまで現在の App が動作します。',importFailed:'導入失敗。現在の App は維持されます。',help:'App と二つの対応プラグインを一組として管理します。切替前に対応プラグインを導入し IDE を再起動／再読み込み。実行中は切替できません。整合性確認は Apple 公証ではありません。'},
    en:{title:'Updates and rollback',current:'Current app',check:'Check GitHub updates',download:'Open downloads',import:'Import an extracted complete release',plugins:'Open paired bridges',switch:'Switch to this version',idle:'Check online or import a local release.',checking:'Checking…',unpublished:'No release manifest is published yet. Local imports are available.',checkFailed:'Online check failed.',available:'New version available',latest:'No newer remote release',verifying:'Verifying and backing up the current version…',imported:'Imported. The current app runs until you switch.',importFailed:'Import failed; the current app is preserved.',help:'App and both bridge packages are managed as a set. Install matching bridges and reload/restart the IDEs before switching. Active tasks block switching. Older bridges still report status; new run actions require matching versions. Integrity checks are not Apple notarization.'}
  };
  function versions() {
    const v=data.versions || {current:'3.8.0',status:'idle',versions:[]},w=versionWords[language()];
    const action=(label,name,id='')=>button(label,'versionAction',`data-action="${name}" ${id?`data-id="${esc(id)}"`:''} ${v.busy?'disabled':''}`);
    return `<details data-version-settings><summary>${esc(w.title)}</summary><p>${esc(w.current)} · ${esc(v.current)}</p><p role="status">${esc(w[v.status] || v.status)}${v.available?' · '+esc(v.available):''}</p>${v.detail?`<p class="fy-notice">${esc(v.detail)}</p>`:''}<div class="fy-actions">${action(w.check,'check')}${action(w.download,'download')}${action(w.import,'import')}</div>${(v.versions || []).map(r=>`<article class="fy-version-row"><strong>${esc(r.version)}</strong><div class="fy-actions">${action(w.plugins,'plugins',r.version)}${action(w.switch,'switch',r.version)}</div></article>`).join('')}<p class="fy-race-label">${esc(w.help)}</p></details>`;
  }
  function renderSettings() {
    const p=data.preferences;
    for(const area of root.querySelectorAll('[data-tool-settings]')) {
      if(area.contains(document.activeElement))continue;
      const opens=[...area.querySelectorAll('details')].map(d=>d.open);
      area.innerHTML=`<details><summary>${esc(t('voice'))}</summary>${checkbox('voiceEnabled','enabled',p)}${checkbox('automaticVoiceEnabled','auto',p)}<label>${esc(t('volume'))}<input aria-label="${esc(t('volume'))}" data-tool-key="voiceVolume" type="range" min="0" max="1" step="0.05" value="${p.voiceVolume??1}"></label>${['click','working','completed','failed','interrupted'].map(c=>`<div class="fy-scene">${checkbox('voiceScene.'+c,c,p)}${button('audition','audition',`data-context="${c}"`)}</div>`).join('')}${checkbox('quietEnabled','quiet',p)}<div class="fy-tool-inline">${select('quietStart',Array.from({length:24},(_,i)=>[i,String(i).padStart(2,'0')+':00']),p)} → ${select('quietEnd',Array.from({length:24},(_,i)=>[i,String(i).padStart(2,'0')+':00']),p)}</div><p class="fy-race-label">${esc(t('hours'))}</p></details><details><summary>${esc(t('mode'))}</summary>${select('companionMode',['normal','focus','meeting'].map(k=>[k,t(k)]),p)}${checkbox('edgePark','edge',p)}</details><details><summary>${esc(t('racing'))}</summary>${checkbox('raceReminders','raceReminders',p)}${checkbox('entryReminders','entryReminders',p)}<label>${esc(t('lead'))}${select('reminderLead',[15,30,60].map(i=>[i,String(i)]),p)}</label><p class="fy-race-label">${esc(t('local'))}</p></details><details><summary>${esc(t('diagnostics'))}</summary>${diagnostics()}</details>`;
      area.insertAdjacentHTML('beforeend',versions());
      area.querySelectorAll('details').forEach((d,i)=>d.open=opens[i] || false);
    }
  }
  function records(values) {
    return values.length?values.map(r=>`<article class="fy-activity"><strong>${esc(r.source)} · ${esc(t(r.state))}</strong><time>${esc(new Date(r.date).toLocaleString(root.lang))}</time><p>${esc(r.title || t(r.state))}</p><small>${esc(r.project)}${r.duration!==null&&r.duration!==undefined?' · '+Math.round(r.duration)+'s':''}</small>${['codex','vscode','pycharm'].includes(r.source)?button('jump','historyJump',`data-id="${esc(r.id)}"`):''}${['vscode','pycharm'].includes(r.source)&&r.state==='failed'?button('problems','historyJump',`data-id="${esc(r.id)}" data-action="openProblems"`):''}</article>`).join(''):`<p>${esc(t('empty'))}</p>`;
  }
  function render(force=false) {
    renderSettings();
    const signature=JSON.stringify([language(),data.history,data.recent,data.preferences,data.races,data.running,data.timer.phase,data.timer.paused]);
    if(force||signature!==fingerprint) {
      fingerprint=signature;
      for(const panel of root.querySelectorAll('[data-panel=tools],[data-uma-panel=tools]')) {
        const minutes=panel.querySelector('[data-timer-minutes]')?.value || '25';
        panel.innerHTML=`<div class="uma-panel-body"><h3>${esc(t('tools'))}</h3><h4>${esc(t('timer'))}</h4><div class="fy-timer-clock" data-timer-clock></div><label>${esc(t('minutes'))}<input type="number" min="1" max="180" value="${minutes}" data-timer-minutes></label><div class="fy-actions">${button('start','timer','data-action="start"')}${button(data.timer.paused?'resume':'pause','timer',`data-action="${data.timer.paused?'resume':'pause'}" ${data.timer.phase==='idle'?'disabled':''}`)}${button('reset','timer','data-action="reset"')}</div><h4>${esc(t('timing'))}</h4><div data-task-clocks></div><h4>${esc(t('history'))}</h4><div class="fy-tool-inline"><select data-history-filter>${['all','codex','vscode','pycharm','timer','racing'].map(s=>`<option value="${s}" ${filter===s?'selected':''}>${esc(s==='all'?t(s):s)}</option>`).join('')}</select>${button('clear','clearHistory')}</div><p class="fy-race-label">${esc(t('notification'))}</p>${records(data.history.filter(r=>filter==='all'||r.source===filter))}<h4>${esc(t('recent'))}</h4>${records(data.recent)}<h4>${esc(t('racing'))}</h4><p class="fy-race-label">${esc(t('local'))}</p>${data.races.length?button('export','exportCalendar'):''}${data.races.map(r=>`<article class="fy-activity"><strong>${esc(language()==='en'&&r.englishName?r.englishName:r.name)}</strong><p>${esc(r.start&&!r.provisionalTime?new Intl.DateTimeFormat(root.lang,{dateStyle:'medium',timeStyle:'short',timeZone:language()==='zh'?'Asia/Shanghai':language()==='ja'?'Asia/Tokyo':r.zone}).format(new Date(r.start)):r.localDate+' · '+t('tba'))}</p><small>${esc(r.venue)} · ${esc(r.entryStatus==='candidate'?t('candidate'):r.entryStatus==='declared'?t('declared'):'')}</small>${button('export','exportCalendar',`data-id="${esc(r.id)}"`)}</article>`).join('') || `<p>${esc(t('empty'))}</p>`}</div>`;
      }
    }
    root.querySelectorAll('[data-timer-clock]').forEach(e=>e.textContent=t(data.timer.phase)+' · '+Math.floor(data.timer.seconds/60)+':'+String(data.timer.seconds%60).padStart(2,'0'));
    root.querySelectorAll('[data-task-clocks]').forEach(e=>e.innerHTML=data.running.length?data.running.map(r=>`<p>${esc(r.key.split(':')[0])} · ${Math.max(0,Math.floor((Date.now()-r.startedAt)/1000))}s</p>`).join(''):`<p>${esc(t('empty'))}</p>`);
  }
  window.petTools={update(payload){if(payload&&Object.keys(payload).length)data={...data,...payload};render();},render:()=>render(true)};
  root.addEventListener('change',event=>{
    const e=event.target;
    if(e.hasAttribute('data-history-filter')){filter=e.value;render(true);return;}
    if(e.dataset.toolKey){const value=e.type==='checkbox'?e.checked:e.type==='range'||['quietStart','quietEnd','reminderLead'].includes(e.dataset.toolKey)?Number(e.value):e.value;send('toolSetting',{key:e.dataset.toolKey,value});}
  });
  root.addEventListener('click',event=>{
    const e=event.target.closest('button');if(!e)return;
    const cmd=e.dataset.command;
    if(['audition','timer'].includes(cmd)) {
      // The main UI also handles known fields; these commands carry tool-specific values here only.
      event.stopImmediatePropagation();send(cmd,{context:e.dataset.context,action:e.dataset.action,minutes:Number(e.closest('[data-panel],[data-uma-panel]')?.querySelector('[data-timer-minutes]')?.value || 25)});
    }
  },true);
  render(true);
})();
