'use strict';
// Offline help for the shipped app and bridge packages. No installer runs from this page.
window.petManual = {
  zh: {
    basics: {title:'桌宠使用', groups:[
      {title:'启动与操作', items:['当前成品支持 Apple Silicon Mac、macOS 14 及以上。解压后退出旧版，再双击桌宠应用；一次只运行一个版本。应用为本地 ad-hoc 签名，未公证，其他 Mac 首次打开可能需要用户确认来源。','鼠标视线跟随、悬停单次跳跃、左右拖动跑步。点击角色会挥手、播放原有问候音频并显示最新状态。下方五个图标依次是工作台、输入、运行、软件联动、关闭气泡。右键或菜单栏也可打开工作台、调整尺寸及退出。']},
      {title:"界面与状态", items:["设置可切换二次元／极简、中／日／英和主要联动来源。联动页顶部显示当前主来源；点击下方软件卡片只切换操作对象与按键，不改变状态优先来源。设置与位置保存在本机。", "自动模式优先已连接的前台软件，再选择最近变化的活跃来源。固定来源未连接时会如实显示未连接；另外两路仍同时接收。", "提醒按失败 → 完成／中断 → 普通状态排序；同级优先主来源，再按到达顺序。新状态首次提醒高于问候，心跳不重复播报。联动状态动作开关影响三路动画，不停止状态接收。"]},
      {title:'赛事与数据', items:['赛事、实马参赛计划与战绩由本机查询官方资料。有时刻时中文显示北京时间、日文东京时间、英文赛场当地时间；未公布时刻保留官方当地日期。国际赛程不是全球全部 GⅠ。','刷新绕过五分钟缓存。清理缓存只删除桌宠自己的赛事缓存，不改 Codex 或 IDE 数据；下一次查询重新联网。断网时旧缓存保留原获取时间。']},
      {title:'给其他使用者', items:['解压或启动桌宠不会自动修改三个软件、安装插件或生成项目运行配置。Codex 使用自己的本机任务；IDE 需自行安装成品内插件并打开项目。插件装入用户扩展目录，IDE 程序文件无需修改。','本地联动不需要另建云端服务器。正常 Codex 推理仍使用自己的已登录账号与服务。Windows、Linux、Intel Mac 暂无此成品的可运行二进制。']}
    ]},
    codex: {title:'Codex 连接', groups:[
      {title:'连接步骤', items:['在同一 Mac、同一 macOS 用户下启动并登录 Codex，创建或打开本地任务；无需新的账号绑定或 API Key。','桌宠自动读取本机任务记录。任务页可固定跟随，也可恢复自动跟随；文字输入锁定当时的任务，发送前会再次确认目标。','下方“检查连接”检查记录读取；“检查官方通道”检查已安装 CLI 的本地 App Server。两种连接状态分别显示。']},
      {title:'发送与权限', items:['已有桌面任务的状态使用只读兼容适配器；直接发送使用官方本地接口，在原任务开启下一轮。快捷操作先填入草稿，需要点击发送。','没有共享官方控制通道时，只能向空闲任务或桌宠自己启动的轮次发送，不能接管其他客户端正在执行的轮次。原客户端任务在原客户端审批；桌宠发起的命令／文件审批弹出确认窗，其余交互请求暂不支持。','任务目录通常是 ~/.codex。自定义 CODEX_HOME 时，须让桌宠继承相同环境。官方 CLI 或内部数据格式更新后可能需要升级桌宠。离线桥接不替代 Codex 推理服务。']}
    ]},
    vscode: {title:'VS Code 连接与运行', groups:[
      {title:'连接插件', items:['在 VS Code 扩展页菜单选择 Install from VSIX…，安装成品“联动插件”内的 forever-young-vscode-3.7.1.vsix；按提示重载窗口。最低版本 1.90。','打开自己的项目文件夹；单独打开一个文件不等于打开项目。插件遵守 Workspace Trust，只信任自己确认安全的工程。桌宠与 IDE 使用同一 macOS 用户。','看到来源卡片与心跳即表示插件连接。连接本身不要求创建 tasks.json；没有运行任务也能显示空闲。']},
      {title:"默认单文件与可选工程操作", items:["日常主按钮默认运行当前编辑文件。VS Code 在前台时，角色下方 Run 也使用该入口。已有本地文件会先自动保存；编译成功后在终端运行并获得输入焦点。C++ 练习无需逐题配置任务；工作目录是源码所在目录。工程运行、构建和测试收在折叠的“高级工程操作”中。", "“运行项目”获取已有 Task／Debug 配置（包括扩展自动检测的任务）。每个工作区首次有多个候选时选择一次，后续自动复用；只有一个候选或唯一默认任务时直接使用。“更换运行目标”只保存选择，不立即执行。取消选择不会运行。", "“运行当前文件”无需 tasks.json，支持保存于本机的 Python、JavaScript、C／C++ 单文件。Python 使用项目所选解释器或现有 .venv；JavaScript 使用已安装 Node.js；C／C++ 使用已有编译器（C17／C++17），编译成功后才运行临时程序，失败不执行旧程序。", "多文件、链接库、特殊编译选项与测试仍使用项目本身的配置；构建／测试分别筛选 group: build／test。运行、构建、测试各自记住目标；目标删除或内容变化后重新选择。桌宠不安装编译器、依赖或解释器，也不生成／覆盖项目配置。"]},
      {title:'反馈范围', items:['Task 开始／退出会反馈工作、成功、失败或中断。Debug API 未提供通用退出码，结束只报停止／中断。普通终端手输命令不属于 Task 事件。停止操作需选择任务。','当前不自动生成或覆盖项目配置，也不自动安装插件。完整操作参考 VS Code 官方 Tasks 与 Extensions 文档，链接见成品 README。']}
    ]},
    pycharm: {title:'PyCharm 连接与运行', groups:[
      {title:'连接插件', items:['在 PyCharm 的 IDE 插件页齿轮菜单选择 Install Plugin from Disk…，安装成品“联动插件”内的 forever-young-pycharm-3.7.0.zip；按提示重启 IDE。要求 PyCharm 2025.1+，本机验证的是 Community 2025.1。','打开项目，沿用项目已有解释器。桌宠与 IDE 使用同一 macOS 用户；插件通过用户目录本地邮箱发送状态，不修改 IDE 程序。']},
      {title:"复用项目运行目标", items:["“运行项目”复用桌宠记住的项目配置；首次优先 IDE 当前选中的配置或唯一候选，多个目标无法确定时选择一次。“更换运行目标”只保存新的选择，随后点击运行。“运行测试”单独记住测试配置。", "没有配置时，先在 PyCharm 对入口执行 Run，或在 Run → Edit Configurations… 保存配置。沿用项目解释器、脚本／模块入口、工作目录与必要参数；无需每次运行重新配置。目标删除或改名后重新选择。", "测试按钮只使用测试类型配置；停止操作确认当前项目的进程，不终止其他项目。当前没有通用的“运行当前文件”与构建接口，因此 PyCharm 页只显示已实现的按键。"]},
      {title:'反馈范围', items:['通过官方 ExecutionListener 接收 IDE 进程的开始与退出。没有启动项目时显示空闲；不监视 IDE 外部任意 Python 程序，也不保存控制台正文。','测试目录中的 pycharm 是普通项目文件夹，不是 PyCharm 应用。当前不自动创建运行配置；官方插件安装与运行配置文档链接见 README。']}
    ]}
  },
  ja: {
    basics: {title:'使い方', groups:[
      {title:'起動と操作', items:['Apple Silicon Mac、macOS 14 以降に対応。展開後、旧版を終了してアプリを開きます。同時に1つの版だけを使用してください。ローカル ad-hoc 署名で未公証のため、別の Mac では初回起動時に確認が必要な場合があります。','視線はマウスを追い、ホバー時は1回だけジャンプ、左右のドラッグでは走ります。クリックで手を振り、既存の挨拶音声と最新状態を表示。5つのアイコンはワークスペース、入力、実行、アプリ連携、吹き出しを閉じる。右クリックやメニューバーでも操作できます。']},
      {title:"表示と状態", items:["設定でアニメ／ミニマル、中文／日本語／English、優先する連携先を選択。連携画面上部は実際の優先先を表示。アプリカードをクリックすると操作対象とボタンだけが切り替わり、通知の優先先は変わりません。設定と位置はこの Mac に保存します。", "自動では接続中の前面アプリ、次に最近変化した実行中の入力を優先。固定した入力が未接続なら未接続と表示します。他の2つも受信を続けます。", "通知は失敗 → 完了／中断 → 通常状態。同順位は優先先、次に到着順。新しい状態を挨拶より先に表示し、ハートビートを繰り返し通知しません。状態アニメの設定をオフにしても受信は継続します。"]},
      {title:'レース情報', items:['公式情報をこの Mac から取得。公表時刻は中文で北京、日本語で東京、English で開催地の時間。時刻未発表なら現地日付のみ。海外の全 GⅠを網羅していません。','更新は5分間のキャッシュを迂回。削除はペットのレースキャッシュだけで、Codex や IDE のデータを変更しません。次の検索で再取得。オフライン時の古いキャッシュには元の取得時刻を表示します。']},
      {title:'ほかの利用者', items:['展開・起動でソフトの変更、プラグイン導入、実行設定の生成を自動で行いません。Codex は自分のローカルタスクを使用。IDE は同梱プラグインをユーザー拡張フォルダへ導入し、プロジェクトを開きます。IDE 本体の変更は不要です。','独自のクラウド中継サーバーは不要。Codex 推論は自分のアカウントとサービスを使用します。現在のバイナリは Windows、Linux、Intel Mac に未対応です。']}
    ]},
    codex: {title:'Codex 接続', groups:[
      {title:'接続手順', items:['同じ Mac、同じ macOS ユーザーで Codex にログインし、ローカルタスクを作成または開きます。新しいアカウント連携や API Key は不要です。','タスク記録を自動取得。タスク画面で追従先を固定、または自動追従に戻せます。入力を開いた時点の宛先を固定し、送信前に再確認します。','「接続を確認」は記録読み取り、「公式接続を確認」は導入済み CLI のローカル App Server を確認します。2つの状態は別々に表示します。']},
      {title:'送信と承認', items:['既存デスクトップの状態は読み取り専用アダプターで受信。直接送信は公式ローカル API で同じタスクの次のターンを開始。ショートカットは下書きなので送信ボタンが必要です。','共有制御チャネルがない場合、待機中かペット自身が開始したターンのみ操作できます。他クライアントの実行中ターンは引き継げません。元のタスクは元クライアントで承認。ペット発のコマンド・ファイル承認は確認画面、他の対話要求は未対応です。','通常の保存場所は ~/.codex。独自の CODEX_HOME では同じ環境から起動してください。公式 CLI や内部形式の更新でペットの更新が必要な場合があります。ローカル連携は Codex 推論サービスの代わりではありません。']}
    ]},
    vscode: {title:'VS Code 接続と実行', groups:[
      {title:'プラグインの接続', items:['拡張機能メニューの Install from VSIX… で同梱の forever-young-vscode-3.7.1.vsix を導入し、案内に従って再読み込み。VS Code 1.90 以降が必要です。','自分のプロジェクトフォルダを開きます。ファイルだけの表示では不十分です。Workspace Trust に従い、安全を確認したプロジェクトだけを信頼。ペットと同じ macOS ユーザーを使います。','連携カードとハートビートがあれば接続済みです。接続だけなら tasks.json の作成は不要で、未実行なら待機を表示します。']},
      {title:"単一ファイルと任意のプロジェクト操作", items:["通常のボタンは現在のファイルを実行。VS Code が前面ならペットの Run も同じ入口です。ローカルファイルを自動保存し、コンパイル成功後にターミナルを実行・フォーカス。C++ の各練習に設定は不要で、作業フォルダはソースの場所です。プロジェクト実行・ビルド・テストは折りたたみ式の高度な操作にあります。", "「プロジェクト実行」は既存・自動検出の Task／Debug 設定を取得。候補が複数ならワークスペースごとに一度選択し、次回から再利用します。唯一の候補・既定タスクは自動選択。「実行対象を変更」は保存だけで実行しません。キャンセル時も実行しません。", "「現在のファイルを実行」は tasks.json 不要。ローカルの Python、JavaScript、C／C++ 単一ファイルに対応。Python は選択済みインタープリターか既存 .venv、JavaScript は既存 Node.js、C／C++ は既存コンパイラー（C17／C++17）を使用。コンパイル成功時だけ一時プログラムを実行します。", "複数ファイル・ライブラリ・特殊オプション・テストはプロジェクトの設定を使用。ビルド／テストは group: build／test を対象とし、実行先を個別に記憶。対象が削除・変更された場合は再選択。ツール導入やプロジェクト設定の生成・上書きは行いません。"]},
      {title:'受信できる状態', items:['Task の開始・終了から実行、成功、失敗、中断を受信。Debug の終了は汎用終了コードがないため停止／中断と表示。通常のターミナル手入力は対象外。停止時はタスクを選択します。','設定の自動生成・上書き、プラグインの自動導入は行いません。公式 Tasks・Extensions 文書へのリンクは README にあります。']}
    ]},
    pycharm: {title:'PyCharm 接続と実行', groups:[
      {title:'プラグインの接続', items:['IDE のプラグイン画面の歯車 → Install Plugin from Disk… で同梱 forever-young-pycharm-3.7.0.zip を導入し、案内に従って再起動。2025.1 以降が必要で、この Mac では Community 2025.1 を検証しました。','プロジェクトを開き、既存のインタープリターを使用。同じ macOS ユーザーのローカルメールボックスで状態を受信し、IDE 本体は変更しません。']},
      {title:"プロジェクトの実行対象を再利用", items:["実行では記憶済み設定を再利用。初回は IDE で選択中の設定か唯一の候補を使用し、複数なら一度選択。「実行対象を変更」は保存のみ、実行は別ボタンです。テストの対象は別に記憶します。", "設定がなければ入口を IDE で Run、または Run → Edit Configurations… で保存。既存インタープリター、入口、作業フォルダ、必要な引数を指定します。毎回の設定は不要。削除・名称変更後は再選択。", "テストはテスト設定のみ。停止時は現在のプロジェクトのプロセスを確認し、他のプロジェクトを終了しません。汎用の現在ファイル実行・ビルド API は未実装のため、対応済みボタンだけを表示します。"]},
      {title:'受信できる状態', items:['公式 ExecutionListener で IDE プロセスの開始・終了を受信。未実行なら待機表示。IDE 外の Python プロセスは監視せず、コンソール本文は保存しません。','テストフォルダ pycharm は普通のプロジェクトで、PyCharm アプリではありません。実行設定の自動作成は未実装。公式ガイドへのリンクは README にあります。']}
    ]}
  },
  en: {
    basics: {title:'Using the pet', groups:[
      {title:'Launch and controls', items:['This build supports Apple Silicon Macs on macOS 14+. Extract it, quit the older version and open the app. Run one version at a time. It is locally ad-hoc signed, not notarized, so another Mac may require confirmation on first launch.','Eyes follow the pointer, hover triggers one jump, and dragging left/right shows running. Clicking waves, plays the existing greeting audio and shows current status. The five icons open the workspace, input, run, app integrations and close the bubble. Right-click and the menu bar provide more controls.']},
      {title:"Appearance and status", items:["Settings controls Anime/Minimal, Chinese/Japanese/English and the primary source. The integration summary shows the primary source. Clicking an app card changes the operation target and its buttons only; notification priority stays unchanged. Preferences and position are local.", "Auto prefers the connected frontmost app, then the most recently changed active source. A disconnected pinned source is shown as disconnected. All three sources remain subscribed.", "Notifications prioritize failure, completion/interruption, then ordinary status; ties prefer the primary source, then arrival order. New status precedes greetings; heartbeats do not repeat notices. Disabling linked animations does not stop reception."]},
      {title:'Racing data', items:['This Mac fetches official schedules, plans and records. Published times use Beijing in Chinese, Tokyo in Japanese and the race venue in English. If no time is published, retain the official local date. International coverage is not a complete global GⅠ calendar.','Refresh bypasses the five-minute cache. Clear cache deletes only pet-owned racing data, leaving Codex and IDE data intact; the next query fetches again. Offline fallback retains its original fetch time.']},
      {title:'Other users', items:['Extracting or launching does not patch apps, install plugins or generate project configurations. Codex uses your own local tasks. Install the included IDE plugins in user extension directories and open a project; core application files need no edits.','No self-hosted cloud bridge is required. Normal Codex inference still uses your signed-in account and service. This binary does not support Windows, Linux or Intel Macs.']}
    ]},
    codex: {title:'Connect Codex', groups:[
      {title:'Connection steps', items:['Sign in to Codex on the same Mac and macOS user account, then create or open a local task. No new account binding or API key is needed.','The pet reads local task records automatically. Pin a task or restore auto-follow on the task page. Input captures its destination when opened and checks it again before sending.','Check connection tests record access; Check official connection tests the installed CLI’s local App Server. Their statuses are displayed separately.']},
      {title:'Sending and approvals', items:['Existing desktop status uses a read-only adapter. Direct input uses the official local API to start another turn in the same task. Shortcuts fill drafts; click Send to execute.','Without a shared control channel, input is limited to idle tasks or turns started by this pet. Active turns owned by another client cannot be taken over. Approve existing client tasks there. Pet-started command/file approvals show confirmation; other interactive requests are unsupported.','The usual task folder is ~/.codex. With a custom CODEX_HOME, launch the pet in the same environment. CLI or internal format changes may require a pet update. The local bridge does not replace the Codex inference service.']}
    ]},
    vscode: {title:'Connect and run in VS Code', groups:[
      {title:'Connect the extension', items:['Use Install from VSIX… in the Extensions menu to install the included forever-young-vscode-3.7.1.vsix, then reload when prompted. VS Code 1.90+ is required.','Open your project folder, not just an individual file. The extension respects Workspace Trust; trust only projects you have verified. Use the same macOS user account as the pet.','A source card and heartbeat indicate connection. Creating tasks.json is not required just to connect; a project with no active task reports idle.']},
      {title:"Single-file default and optional project tools", items:["The primary button runs the current editor file. The pet Run icon does the same while VS Code is frontmost. Local files are saved before execution; after successful compilation the program runs in a focused terminal for input. C++ exercises need no per-file task configuration. The working directory is the source directory. Project run/build/test remain in the collapsed advanced section.", "Run project discovers existing and provider-detected Task/Debug configurations. Choose once per workspace when several candidates exist; subsequent runs reuse it. A sole candidate or unique default task is selected automatically. Change run target saves a choice without executing. Cancelling executes nothing.", "Run current file needs no tasks.json and supports local Python, JavaScript and C/C++ single files. Python uses the selected project interpreter or existing .venv; JavaScript uses existing Node.js; C/C++ uses an existing compiler (C17/C++17). A temporary program runs only after compilation succeeds. Failed compilation never runs an old binary.", "Multi-file projects, libraries, special options and tests use their own configurations. Build/test filter group: build/test. Run/build/test remember independent targets; removed or changed targets require reselection. The pet neither installs tools/dependencies/interpreters nor generates or overwrites project configuration."]},
      {title:'Feedback scope', items:['Task start/exit provides working, success, failure or interruption. Debug termination has no general exit code, so it reports stopped/interrupted. Free-form terminal commands are outside task events. Stopping requires selecting a task.','The pet does not automatically create/overwrite configurations or install extensions. Official Tasks and Extensions references are linked in the README.']}
    ]},
    pycharm: {title:'Connect and run in PyCharm', groups:[
      {title:'Connect the plugin', items:['In the IDE Plugins page, use the gear menu → Install Plugin from Disk… with the included forever-young-pycharm-3.7.0.zip, then restart when prompted. Requires 2025.1+; Community 2025.1 was tested on this Mac.','Open a project with its existing interpreter. The pet and IDE share a user-local mailbox under the same macOS account; core IDE files are not patched.']},
      {title:"Reuse the project run target", items:["Run project reuses the remembered configuration. The first run uses the IDE-selected configuration or sole candidate, otherwise asks once. Change run target only saves a choice; click Run afterwards. Tests remember a separate target.", "If none exists, Run the entry point in PyCharm or save one through Run → Edit Configurations… using the project interpreter, script/module, working directory and arguments. No per-execution setup is required. Removed or renamed targets require reselection.", "Tests use test configuration types. Stop confirms processes in the selected project, without stopping other projects. Generic current-file/build operations are not implemented for PyCharm, so only supported controls are displayed."]},
      {title:'Feedback scope', items:['The official ExecutionListener supplies IDE process start and exit events. With no process, the source is idle. Arbitrary Python programs outside the IDE are not monitored; console content is not stored.','The test folder named pycharm is an ordinary project, not the PyCharm application. Automatic configuration generation is not implemented. Official installation and run-configuration references are linked in the README.']}
    ]}
  }
};
